config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    collection do
      get :search, to: 'cocktails#search'
    end
  end
  resources :doses, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :title, :content, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update]

  def index
    @homepage = true
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
  end

  def new
    @btn_create_cocktail_disabled = true
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(params_cocktail)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @cocktail.update(params_cocktail)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def search
    if params[:keyword].present?
      sql_query = " \
        cocktails.name ILIKE :keyword \
        OR ingredients.name ILIKE :keyword \
      "
      @cocktails = Cocktail.joins(:ingredients).distinct.where(sql_query, keyword: "%#{params[:keyword]}%")
    else
      @cocktails = Cocktail.all
    end
    # @cocktails = Cocktail.where('name ILIKE ?', "%#{params[:keyword]}%")
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def params_cocktail
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def index
    @doses = Dose.all
  end

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(params_dose)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def params_dose
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(params_review)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def params_review
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%# <hr>
  <h3>Ingredients</h3>
  <%= f.simple_fields_for(@dose) do |f_dose| %>
  <%#  <%= f_dose.association :ingredient, collection: Ingredient.order(:name), prompt: 'Choose an ingredient', input_html: { class: 'select2' } %>
  <%#  <%= f_dose.input :description %>
  <%# <% end %>
  <%# <%= link_to 'Add an ingredient', class: 'btn btn-outline-primary' %>
  <%# <hr> %>
  <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/cocktails/_search_form.html.erb
<%= form_with url: "/cocktails/search", method: :get, class: "search-bar" do |form| %>
  <input class="form-control mr-sm-2" type="search" placeholder="Search by name or ingredients" aria-label="Search" name="keyword" id="search-input">
  <button class="btn btn-primary my-2 my-sm-0 mr-2" type="submit"><i class="fas fa-search"></i></button>
<% end %>

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="default-card form-card">
    <h1 class="mb-3">Edit the '<%= @cocktail.name %>' cocktail</h1>
    <%= render 'form', locals: { cocktail: @cocktail } %>
    <%= link_to 'Back to cocktail', cocktail_path(@cocktail), class: 'btn btn-outline-primary mt-3' %>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <h1 class="home-title">Discover our cocktails</h1>

  <div class="cocktail-cards-grid">
    <% @cocktails.each do |cocktail| %>
      <div class="cocktail-card">
        <div class="card-title"><%= cocktail.name %></div>
        <%= link_to 'More info', cocktail_path(cocktail), class: 'btn btn-primary' %>
        <%= link_to 'Edit', edit_cocktail_path(cocktail), class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="default-card form-card">
    <h1 class="mb-3">Create a new cocktail</h1>
    <%= render 'form', locals: { cocktail: @cocktail } %>
  </div>
</div>

app/views/cocktails/search.html.erb
<div class="container"> 
  <div class="cocktail-cards-grid">
    <% @cocktails.each do |cocktail| %>
      <%= link_to cocktail_path(cocktail) do %>
        <div class="default-card cocktail-card" style="background-image: url('<%= cloudinary_url(cocktail.photo.key, width: 720, height: 720, crop: :fill) %>')">
          <div class="cocktail-card-title"><%= cocktail.name.capitalize %></div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %> <%= link_to 'Edit', edit_cocktail_path(@cocktail), class: 'btn btn-outline-primary ml-2' %></h1>

  <div class="cocktail-show-card">

    <div class="cocktail-show-card-ingredients">
      <h3>Ingredients</h3>
      <ul>
        <% @doses.each do |dose| %>
          <li>
            <%= dose.description.downcase %> <%= dose.ingredient.name.downcase %> 
            <span class="btn-delete"><i class="far fa-trash-alt"></i></span>
            <%= link_to "", dose_path(dose), method: :delete, id: "delete-link", class: "hidden" %>
          </li>
        <% end %>
      </ul>
      <%= link_to 'Add an ingredient', new_cocktail_dose_path(@cocktail), class: 'btn btn-outline-primary' %>
    </div>

    <% if @cocktail.photo.attached? %>
      <%= cl_image_tag @cocktail.photo.key, crop: :fill %>
    <% end %>

  </div>

  <div class="default-card mt-4">
    <%= link_to 'Add a review', new_cocktail_review_path(@cocktail), class: 'btn btn-primary' %>
    
    <% if @cocktail.reviews.size > 0 %>

      <div class="cocktail-reviews">

        <% @cocktail.reviews.each do |review| %>
          <div class="cocktail-review">

            <div class="cocktail-review-header">
              <div class="cocktail-review-header-rating">
                <% review.rating.times do %>
                  <i class="fas fa-star star"></i>
                <% end %>
              </div>
              <div class="cocktail-review-header-title">
                <%= review.title %>
              </div>
            </div>

            <div class="cocktail-review-date">
              <%= review.created_at.strftime("Posted on %m/%d/%Y") %>
            </div> 

            <div class="cocktail-review-content">
              <%= review.content %>
            </div>

          </div>
        <% end %> 

      </div>

    <% end %>

  </div>

</div>

app/views/doses/_form.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.association :ingredient, collection: Ingredient.order(:name), prompt: 'Choose an ingredient', input_html: { class: 'select2' } %>
  <%= f.input :description, placeholder: 'Ex: 12cl' %>
  <hr>
  <%= f.submit 'Add a dose', class: 'btn btn-primary mb-2' %>
<% end %>

app/views/doses/new.html.erb
<div class="container">
  <div class="default-card form-card">
    <h1 class="mb-3">New dose for '<%= @cocktail.name %>'</h1>
    <%= render 'form', locals: { cocktail: @cocktail, dose: @dose } %>
    <%= link_to 'Back to cocktail', cocktail_path(@cocktail), class: 'btn btn-outline-primary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worth a shot 🍹</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="<%= 'pages' unless @homepage %>" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@cocktail, @review]) do |f| %>
  <%= f.label :rating %>
  <div class="rating">
    <%# <%= f.collection_radio_buttons :rating, [[1, '1'] ,[2, '2'],[3, '3'],[4, '4'],[5, '5']], :first, :last %>
    <%= f.simple_fields_for :rating do %> 
      <label>
        <input type="radio" name="review[rating]" value="5" title="5 stars"> 5
      </label>
      <label>
        <input type="radio" name="review[rating]" value="4" title="4 stars"> 4
      </label>
      <label>
        <input type="radio" name="review[rating]" value="3" title="3 stars"> 3
      </label>
      <label>
        <input type="radio" name="review[rating]" value="2" title="2 stars"> 2
      </label>
      <label>
        <input type="radio" name="review[rating]" value="1" title="1 star"> 1
      </label>
    <% end %>
  </div>
  <%= f.input :title, placeholder: 'What is the most important to know?' %>
  <%= f.input :content, placeholder: 'Describe your taste : what did you like or dislike?' %>
  <hr>
  <%= f.submit 'Add a review', class: 'btn btn-primary mb-2' %>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
  <div class="default-card form-card">
    <h1 class="mb-3">Add a new review</h1>
    
    <div class="cocktail-recall">
      <% if @cocktail.photo.attached? %>
        <div class="cocktail-recall-img">
          <%= cl_image_tag @cocktail.photo.key, crop: :fill, style:'width: 100%' %>
        </div>
      <% end %>
      <div class="cocktail-recall-name">
        <%= @cocktail.name %>
      </div>
    </div>

    <hr>

    <%= render 'form', locals: { cocktail: @cocktail, review: @review } %>
    <%= link_to 'Back to cocktail', cocktail_path(@cocktail), class: 'btn btn-outline-primary' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top <%= 'navbar-home' if @homepage %> <%= 'navbar-white' unless @homepage %>"> 
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% 
      navbar_brand_class_home = @homepage ? 'navbar-brand-was-white' : 'navbar-brand-was-primary'
      navbar_brand_class = "navbar-brand-was #{navbar_brand_class_home}"
    %>
    <%= link_to 'Worth a shot', root_path, id: 'navbar-brand', class: navbar_brand_class %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <%# <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul> %>
      <%# <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary my-2 my-sm-0 mr-2" type="submit">Search</button>
      </form> %>
      <% unless @btn_create_cocktail_disabled %>
        <%= link_to 'Create a cocktail', new_cocktail_path, id: 'btn-add-cocktail', class: @homepage ? 'btn btn-outline-secondary' : 'btn btn-outline-primary' %>
      <% end  %>
    </div>
  </div>
</nav>